#!/bin/sh 

gulp build --release --destination github
git checkout gh-pages
rm -rf assets
cp -R ./build/* ./

git add -A
git commit -m "chore(release): release to github pages"
git push origin gh-pages
